services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: 2ktPjIynHzcI1EOqgdmEhTYd4oqiJzu4
      MINIO_ROOT_PASSWORD: 9rdvlnc8OxgyhBYA2Ub5noaHiFeUekyU
    command: server /data --console-address ":9001"
